FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    vsftpd curl tcpdump iproute2 net-tools procps wget ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["sleep", "infinity"]