FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    tcpdump iproute2 iputils-ping net-tools curl less vim bash-completion \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /pcaps

CMD ["sleep", "infinity"]